### ISSUE TITLE
second Number

### ISSUE THREAD

**Issue by Gernair** [inUtil-info/node-red-contrib-whin#40] opened 2022-08-23 17:39 UTC
Hi, 

i need a Token for a sekond Phone. 

i send "signup" 

the answer is 

To use WHIN, you must first sign up to get your service token by sending the word signup.

**Comment by Gernair** [comment] 2022-08-23 17:48
I have 2 phones with 2 different numbers.
on the first phone I sent Signup and immediately got a token.
I did the same thing with the 2nd phone, but here I keep getting the message that I should first send the word signup

Can you help me.

**Comment by lu4t** [comment] 2022-08-24 07:52
This must be a difference in the WhatsApp version of the app installed on each. Let's do this:
- first: Make sure you update the version of the app.
- second: send a signup msg and check if you get a token. If you don't get it:
- take note of the date / hour you sent it and post it here, together with the last 5 numbers of the phone that is not working.

We will have a look and see if there is any problem with the metadata not parsing correctly.
Your problem is easy to get solved.

**Comment by Gernair** [comment] 2022-08-27 10:14
Hello, thanks for the help

Whats app is current version 2.22.17.76
I tried again today.
Unfortunately again no token
Attempt was on 08/27/2022 at 12:08 German time
The last 5 digits of the phone number are "94207"

Many Thanks

**Comment by lu4t** [comment] 2022-08-27 15:35
it's weird, I can see your signup request on the logs,... but you're right as the whin token was not created.
I don't see any problem on your side, so the root cause is very likely on our end.
While we investigate, and as a workaround, I would recommend you try to get the token using whatsapp web for that number (not the app on the phone). Once you get the token, you should not have any problem sending/receiving.
I will leave this issue open till we find out the reason.

**Comment by Gernair** [comment] 2022-08-29 06:16
Hi,

I've tried both WhatsApp versions.
By phone and by PC
I'll try again today when I'm home.
Thank you for your support

**Comment by Gernair** [comment] 2022-08-29 17:08
Hi,
I tried again today at 19:06 German time.
Once via WhatsApp Web and once via mobile phone.
Unfortunately, both didn't work out again.

**Comment by lu4t** [comment] 2022-08-29 17:54
I think I found the problem. 

For some weird reason, the msgs you're sending from that particular number have a different structure:


`{"key":{"remoteJid":"4XXXX4207@s.whatsapp.net","fromMe":false,"id":"3EB0C3XXXXXXXF370"},"messageTimestamp":1661792786,"pushName":"NXXXXe","message":{"extendedTextMessage":{"text":"signup","contextInfo":{"expiration":86400,"ephemeralSettingTimestamp":"1660654363","disappearingMode":{"initiator":"INITIATED_BY_ME"}}},"messageContextInfo":{"deviceListMetadata":{"senderKeyHash":"QHcXXXXXXXXeJbg==","senderTimestamp":"1661025261","recipientKeyHash":"BdXXXXXXXO6+tg==","recipientTimestamp":"1661762907"},"deviceListMetadataVersion":2}}}`

@alsak0de, can you please have a look at this? the "signup" text comes inside message.extendedTestMessage as "text":"signup" instead of how they usually come in. I guess we should have to adjust the parsing.

@Gernair, just for our own info: are you sure you're using a regular whatsapp client?. We have thousands of people using whin, and you're the only one that is sending whatsapps with this msg structure. Not a problem for us, just asking...

**Comment by Gernair** [comment] 2022-08-30 06:18
Hi,
I have an Apple iPhone and it worked perfectly the first time.
My wife has a Samsung Galaxy cell phone and downloaded Whats App from the Play Store.
I don't know how else to get WhatsApp.
My wife also has the same WhatsApp version as me.
Should I uninstall and reinstall WhatsApp?
Or what can I do to help you ?

**Comment by lu4t** [comment] 2022-08-30 08:30
you don't need to do anything else, do not worry it's okay. There's something we need to change on the backend so that the signup is working for the second number.
The weird thing is that the msg structure is different even if you use whatsapp web (not related to a given phone vendor)... But again, you're good.
We will close the issue when it's done, first we need to adjust slightly the code.

**Comment by lu4t** [comment] 2022-09-09 11:23
same as #41 and #42

**Comment by lu4t** [comment] 2022-09-09 12:52
see #42

**Closed as completed by lu4t** 2022-09-09 12:52 UTC
